services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./assets/templates:/app/assets/templates
      - ./assets/outputs:/app/assets/outputs
      - ./app:/app/app
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    depends_on: []
