user_name: Huy
communication_language: English
document_output_language: English
output_folder: '{project-root}/_bmad-output'
planning_artifacts: '{project-root}/_bmad-output/planning'
project_knowledge: '{project-root}/docs'
project_name: CVMaker
