from typing import Any, Protocol


class DatabaseProtocol(Protocol):
    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def execute(self, statement: Any) -> Any: ...

    async def fetch_one(self, statement: Any) -> Any | None: ...

    async def fetch_all(self, statement: Any) -> list[Any]: ...
