from typing import Protocol


class StorageProtocol(Protocol):
    async def save(self, path: str, content: bytes) -> str: ...

    async def load(self, path: str) -> bytes: ...

    async def delete(self, path: str) -> None: ...

    async def exists(self, path: str) -> bool: ...
