from typing import Final

MAX_PROFILES: Final[int] = 1000
MAX_SECTIONS_PER_PROFILE: Final[int] = 50
MAX_ENTRIES_PER_SECTION: Final[int] = 100
MAX_CONTACTS_PER_PROFILE: Final[int] = 20
MAX_TEMPLATE_DISCOVERY_ITERATIONS: Final[int] = 1000
