from typing import Final

MAX_PROFILES: Final[int] = 1000
MAX_SECTIONS_PER_PROFILE: Final[int] = 50
MAX_ENTRIES_PER_SECTION: Final[int] = 100
MAX_CONTACTS_PER_PROFILE: Final[int] = 20
MAX_TEMPLATE_DISCOVERY_ITERATIONS: Final[int] = 1000
PROFILE_NAME_MAX_LEN: Final[int] = 255
PROFILE_DESCRIPTION_MAX_LEN: Final[int] = 1000
PDFLATEX_HEALTH_CHECK_TIMEOUT_SECONDS: Final[float] = 5.0
EXPERIENCE_TITLE_MAX_LEN: Final[int] = 255
EXPERIENCE_ORGANISATION_MAX_LEN: Final[int] = 255
EXPERIENCE_DATE_MAX_LEN: Final[int] = 20
EXPERIENCE_ENTRY_CONTENT_MAX_LEN: Final[int] = 1000
EDUCATION_TITLE_MAX_LEN: Final[int] = 255
EDUCATION_ORGANISATION_MAX_LEN: Final[int] = 255
EDUCATION_DATE_MAX_LEN: Final[int] = 20
EDUCATION_ENTRY_CONTENT_MAX_LEN: Final[int] = 1000
